### ISSUE TITLE
JSON schemas with a `required`  attribute cause `coc-yaml` to break the LSP contract on `textDocument/completion` request

### ISSUE THREAD

**Issue by psacawa** [neoclide/coc-yaml#63]
coc.nvim: 0.0.81
coc-yaml: 1.7.5 (the bug does not appear on 1.6.1)

When using JSON schema documents with a `required` attribute, `coc-yaml` incorrectly generates that value as completion item. This ultimately leads to `coc.nvim` complaining that the  server gave a completion item with a label attribute, [against the LSP spec] (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem). 

This can be observed by editing e.g. github workflows yaml files: I've made a [screencast](https://asciinema.org/a/qsEzHrE1h8EGLNb6kvDygptoh). 

[![asciicast](https://asciinema.org/a/qsEzHrE1h8EGLNb6kvDygptoh.svg)](https://asciinema.org/a/qsEzHrE1h8EGLNb6kvDygptoh)

The cast shows the following:

- I inspect the JSON schema document, showing the fragment `"required": ["on", "jobs"]`.
- I edit an arbitrary yaml file `merge-upstream.yml` that uses the schema, and try to do a completion, receiving an error  like
```
2022-06-27T18:40:13.946 ERROR (pid:152449) [node-client] - Cannot read properties of undefined (reading 'trim') TypeError: Cannot read properties of undefined (reading 'trim')
    at LanguageSource.convertVimCompleteItem (/home/psacawa/.vim/bundle/coc.nvim/build/index.js:62595:32)
    at /home/psacawa/.vim/bundle/coc.nvim/build/index.js:62468:27
    at Array.map (<anonymous>)
    at LanguageSource.doComplete (/home/psacawa/.vim/bundle/coc.nvim/build/index.js:62467:35)
2022-06-27T18:40:13.946 ERROR (pid:152449) [completion-complete] - Complete error: yaml TypeError: Cannot read properties of undefined (reading 'trim')
    at LanguageSource.convertVimCompleteItem (/home/psacawa/.vim/bundle/coc.nvim/build/index.js:62595:32)
    at /home/psacawa/.vim/bundle/coc.nvim/build/index.js:62468:27
    at Array.map (<anonymous>)
    at LanguageSource.doComplete (/home/psacawa/.vim/bundle/coc.nvim/build/index.js:62467:35)
```

- I open the servers responses with `workspace.showOutput coc-yaml`. There, I find that in response to `textDocument/completion`, it gave a completion item like

```
        {
            "insertText": "on\njobs:\n  ",
            "insertTextFormat": 2,
            "documentation": {
                "kind": "markdown",
                "value": "The name of the GitHub event that triggers the workflow. You can provide a single event string, array of events, array of event types, or an event configuration map that schedules a workflow or restricts the execution of a workflow to specific files, tags, or branch changes. For a list of available events, see https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows.\n\n----\n\n```yaml\non\njobs:\n  \n```"
            },
            "textEdit": {
                "range": {
                    "start": {
                        "line": 3,
                        "character": 0
                    },
                    "end": {
                        "line": 3,
                        "character": 1
                    }
                },
                "newText": "on\njobs:\n  "
            },
            "sortText": "_undefined",
            "kind": 7
        },
```

which seems to be the result of erroneously taking the `required` attribute of the JSON schema and turning it into a completion item.

**Comment by psacawa** [comment]
I guess this could likely be solved by updating the vendored yaml language server in `dist/language-server.js` to the present version.
