### ISSUE TITLE
Cannot get yaml-language-server to start

### ISSUE THREAD

**Issue by avimmer** [neoclide/coc-yaml#75]
The plugin seems to be not working after installation against a yaml file. After `:CocInstall coc-yaml` I receive an error message saying it couldn't connect to the language server. `:CocOpenLog` says
```
2023-06-19T12:43:31.513 INFO (pid:43070) [model-download] - Downloaded https://registry.npmjs.org/coc-yaml/-/coc-yaml-1.9.0.tgz => /Users/REDACTED/.config/coc/extensions/node_modules/coc-yaml-7469f37f-bd5c-453a-825b-fe41213fea4c
2023-06-19T12:43:32.494 INFO (pid:43070) [services] - LanguageClient YAML Support state change: stopped => starting
2023-06-19T12:43:32.497 INFO (pid:43070) [language-client-index] - Language server "yaml" started with undefined
2023-06-19T12:43:32.499 INFO (pid:43070) [services] - LanguageClient YAML Support state change: starting => stopped
2023-06-19T12:43:32.499 INFO (pid:43070) [services] - LanguageClient YAML Support state change: stopped => starting
2023-06-19T12:43:32.499 ERROR (pid:43070) [language-client-client] - Server yaml initialization failed. jh [Error]: Pending response rejected since connection got disposed
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:51:4592[90m)[39m
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:241:6209[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15575[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:248:3561[90m)[39m
    at t [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15224[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m
    at Qe [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:25:6504[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m {
  code: [33m-32097[39m,
  data: [90mundefined[39m
}
2023-06-19T12:43:32.500 INFO (pid:43070) [services] - LanguageClient YAML Support state change: starting => stopped
2023-06-19T12:43:32.500 ERROR (pid:43070) [server] - unhandledRejection  Promise {
  [36m<rejected>[39m jh [Error]: Pending response rejected since connection got disposed
      at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:51:4592[90m)[39m
      at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:241:6209[90m)[39m
      at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15575[90m)[39m
      at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:248:3561[90m)[39m
      at t [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15224[90m)[39m
      at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
      at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m
      at Qe [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:25:6504[90m)[39m
      at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
      at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m {
    code: [33m-32097[39m,
    data: [90mundefined[39m
  }
} jh [Error]: Pending response rejected since connection got disposed
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:51:4592[90m)[39m
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:241:6209[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15575[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:248:3561[90m)[39m
    at t [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15224[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m
    at Qe [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:25:6504[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m {
  code: [33m-32097[39m,
  data: [90mundefined[39m
}
2023-06-19T12:43:32.501 INFO (pid:43070) [language-client-index] - Language server "yaml" started with undefined
2023-06-19T12:43:32.502 INFO (pid:43070) [services] - LanguageClient YAML Support state change: stopped => starting
2023-06-19T12:43:32.502 ERROR (pid:43070) [language-client-client] - Server yaml initialization failed. jh [Error]: Pending response rejected since connection got disposed
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:51:4592[90m)[39m
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:241:6209[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15575[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:248:3561[90m)[39m
    at t [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15224[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m
    at Qe [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:25:6504[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m {
  code: [33m-32097[39m,
  data: [90mundefined[39m
}
2023-06-19T12:43:32.503 INFO (pid:43070) [services] - LanguageClient YAML Support state change: starting => stopped
2023-06-19T12:43:32.503 ERROR (pid:43070) [services] - Server yaml failed to start: jh [Error]: Pending response rejected since connection got disposed
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:51:4592[90m)[39m
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:241:6209[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15575[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:248:3561[90m)[39m
    at t [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15224[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m
    at Qe [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:25:6504[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m {
  code: [33m-32097[39m,
  data: [90mundefined[39m
}
2023-06-19T12:43:32.504 INFO (pid:43070) [language-client-index] - Language server "yaml" started with undefined
2023-06-19T12:43:32.506 INFO (pid:43070) [services] - LanguageClient YAML Support state change: stopped => starting
2023-06-19T12:43:32.506 ERROR (pid:43070) [language-client-client] - Server yaml initialization failed. jh [Error]: Pending response rejected since connection got disposed
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:51:4592[90m)[39m
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:241:6209[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15575[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:248:3561[90m)[39m
    at t [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15224[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m
    at Qe [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:25:6504[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m {
  code: [33m-32097[39m,
  data: [90mundefined[39m
}
2023-06-19T12:43:32.507 INFO (pid:43070) [services] - LanguageClient YAML Support state change: starting => stopped
2023-06-19T12:43:32.507 INFO (pid:43070) [language-client-index] - Language server "yaml" started with undefined
2023-06-19T12:43:32.509 ERROR (pid:43070) [language-client-client] - Server yaml initialization failed. jh [Error]: Pending response rejected since connection got disposed
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:51:4592[90m)[39m
    at Object.dispose [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:241:6209[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15575[90m)[39m
    at Nd.handleConnectionClosed [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:248:3561[90m)[39m
    at t [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:244:15224[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m
    at Qe [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:25:6504[90m)[39m
    at yT.invoke [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:14460[90m)[39m
    at lc.fire [90m(/Users/REDACTED/[39m.local/share/nvim/plugged/coc.nvim/build/index.js:24:15230[90m)[39m {
  code: [33m-32097[39m,
  data: [90mundefined[39m
}
```

**Comment by chemzqm** [comment]
Could be dependencies of coc-yaml not installed
